
[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrains Mono"

[window]
decorations = "transparent"

[window.padding]
x = 10
y = 32

[general]
import = ["/Users/ruan/.local/share/alacritty/themes/gruvbox_material_hard_dark.toml"]
