# theme = "gruvbox_light"
theme = "gruvbox_dark_hard"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
rulers = [80, 100]
scroll-lines = 1
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-inlay-hints = true
display-messages = true
